### ISSUE TITLE
Swap to using Chalk for colours

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/pulldown#39]
https://github.com/sindresorhus/chalk

**Comment by tgvashworth** [comment]
Ooh, nice. I can see myself using this in future.

**Comment by jackfranklin** [comment]
Yeah me too. Good old @sindresorhus <3

**Comment by sindresorhus** [comment]
:smiley:

**Comment by sindresorhus** [comment]
Some other things we use that might be of interest:
- [update-notifier](https://github.com/yeoman/update-notifier) - a non-obtrusive way to let the user know they have an outdated version.
- [insight](https://github.com/yeoman/insight) for reporting anonymous stats to get a better insight into how your users use the tool. Like what commands are the most used ones, what are never used. What packages are most popular, etc.
- [sudo-block](https://github.com/sindresorhus/sudo-block) - blocks the user from using your app with `sudo`. Since it can cause all kinds of problems.

Also, nice work on the tool! I could see myself using it when prototyping for quickly pulling down common libs.

**Comment by tgvashworth** [comment]
@sindresorhus Nice! I will _definitely_ be giving those a look. Thanks!
